#!/usr/bin/env bash

SCRIPT_PATH="$0"; while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=$(readlink "$SCRIPT_PATH"); done
. "$(dirname $SCRIPT_PATH)/modules/functions.sh"

# prevent master commits
. "$HOOKS_DIR/modules/prevent-master-commits.sh"
if [ $? -ne 0 ]; then
    exit 1
fi

# prevent-merge-marker-commits
. "$HOOKS_DIR/modules/prevent-merge-marker-commits.sh"
if [ $? -ne 0 ]; then
    exit 1
fi

# lein test
. "$HOOKS_DIR/modules/lein-test.sh"
if [ $? -ne 0 ]; then
    exit 1
fi
